### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by mrzhangzizhen123** [asmitapoddar/uncertainty-estimation-DR#1]
hi，can you give me your all code? I find it is not full.thankyou

**Comment by asmitapoddar** [comment]
What do you find lacking?

**Comment by mrzhangzizhen123** [comment]
Where to put the data path?Can you provide the data path?I have kaggle's data set, and I don't know how to put it in, and I can't pre-process it.Can you give me a hand?thank you

**Comment by asmitapoddar** [comment]
In [train.py](https://github.com/asmitapoddar/uncertainty-estimation-DR/blob/master/train.py), the variable `data_dir` stores the data path. The pre-processing (cropping, resizing etc.) also happens in this script, when the data is converted to a tensor. You can store your data path in `data_dir`, and run [train.py](https://github.com/asmitapoddar/uncertainty-estimation-DR/blob/master/train.py). Hope this helps.

**Comment by mrzhangzizhen123** [comment]
@asmitapoddar thanks to your reply.I used the kaggle images,it has 5 kinds such as 0,1,2,3,4.how deal with these data?

**Comment by asmitapoddar** [comment]
Put the images of each kind in its respective folder. For example, put all images of class 0 in folder '0', class 1 in folder '1' and so on. Then put these 5 folders in a 'data' folder and provide its path in the code as instructed.

**Comment by mrzhangzizhen123** [comment]
thank you ,according to your reply.it is not successful.I put the 5 folders 0,1,2,3,4 in the data folder, and then I ran train.py and found that there were no trains and val folders.Then I saw these two folders and found no pictures in them.

**Comment by asmitapoddar** [comment]
You also have to create 'val' and 'test' folders, each containing class 0,1, 2, 3, 4 images - similar to how you have created the 'train' folder, Then put these three folders- 'train', 'val' and 'test' into a folder called 'data', and provide the path of the 'data' folder as mentioned above.

**Comment by mrzhangzizhen123** [comment]
Can you tell me your dataest?The number of pictures of 01234 under "train", "val" and "test".

**Comment by mrzhangzizhen123** [comment]
my dataest have 88702 images

**Comment by asmitapoddar** [comment]
I did not use Kaggle images to train my model. My training set had a different source. You would need to segregate your images into 0,1, 2, 3, 4, and create the dataset splits as explained above.

**Comment by mrzhangzizhen123** [comment]
can you give me your data？------------------ 原始邮件 ------------------
发件人: "Asmita Poddar"<notifications@github.com>
发送时间: 2019年5月31日(星期五) 下午5:19
收件人: "asmitapoddar/uncertainty-estimation-DR"<uncertainty-estimation-DR@noreply.github.com>;
抄送: "mrzhangzizhen123"<639521600@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [asmitapoddar/uncertainty-estimation-DR] about data (#1)



I did not use Kaggle images to train my model. My training set had a different source. You would need to segregate your images into 0,1, 2, 3, 4, and create the dataset splits as explained above.
 
&mdash;

**Comment by asmitapoddar** [comment]
Sorry, my data is not public and cannot be distributed.

**Comment by mrzhangzizhen123** [comment]
Many thanks for your reply. I would like to experiment with kaggle dataset. Could you tell me how to process these data?

**Comment by mrzhangzizhen123** [comment]
Is your data in.png format?Kaggle's data is.jpeg.

**Comment by asmitapoddar** [comment]
My data is in .png format. .jpeg format also should not be an issue. Make sure that your images are of dimension 256 X 256 before running the code.

**Comment by mrzhangzizhen123** [comment]
Resnet network image dimension is 256*256?If I use InceptionV3, is the image dimension 299*299?

**Comment by mrzhangzizhen123** [comment]
Excuse me, I'm having this problem in the run pedicple.py.Can you help me ?
user3@ubuntu:~/uncertainty-estimation-DR-master$ python ./prediction.py 
Traceback (most recent call last):
  File "./prediction.py", line 6, in <module>
    import utils
  File "/home/user3/uncertainty-estimation-DR-master/utils.py", line 8, in <module>
    from networks.stochbn import _MyBatchNorm
ModuleNotFoundError: No module named 'networks.stochbn'

**Comment by asmitapoddar** [comment]
I have uploaded the necessary file to the folder 'networks'
